# Site settings
title: 'Take Note : Simple Note Taking Made Easy'
email: developer@nocturnalcode.com
description: > # this means to ignore newlines until "baseurl:"
  Take Note is a simple note taking App for iOS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://take-note.io" # the base hostname & protocol for your site
twitter_username: NocturnalCode
github_username:  NocturnalCode

app_id: 967873702
app_url: 'https://itunes.apple.com/us/app/take-note-simple-note-taking/id967873702?ls=1&mt=8'

# Build settings
markdown: kramdown
